name: Test Workflow Trigger
on: workflow_dispatch #for manual testing

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'master_ppfflaskapp.yml',
              ref: 'master',
              inputs: {}
            })
